name: CMake Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.21.3'
  
    - name: Configure CMake
      run: cmake -B build

    - name: Build
      run: cmake --build build --target unit_tests

    - name: Run Tests (Linux/macOS)
      if: runner.os != 'Windows'
      run: ./build/unit_tests

    - name: Run Tests (Windows)
      if: runner.os == 'Windows'
      run: .\build\Debug\unit_tests.exe
