name: Coverage

on: [push, pull_request]

jobs:
  compute-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.21.3'
  
    - name: Build and test this project
      run: |
        cmake . -B build -DCOMPUTE_CODE_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --target unit_tests
        ctest --test-dir build
    
    - name: Install gcovr and generate the coverage file in Cobertura format
      run: |
        sudo apt-get install gcovr
        gcovr -r . --xml -o coverage.xml --exclude-unreachable-branches --exclude-throw-branches \
          --filter 'src/.*\.cpp$' \
          --filter 'include/.*/.*\.hpp$' \
          --exclude 'src/main.cpp'

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        files: ./coverage.xml

